/**
 * End-to-end over HTTP: the UI must be off by default, gated behind a session,
 * CSRF-protected, rate limited, and it must never render an unescaped
 * institution-supplied string.
 */
import { mkdtempSync } from 'node:fs';
import { inlineHandlers } from './helpers.ts';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { AddressInfo } from 'node:net';
import type { Server } from 'node:http';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const USER = 'ramesh';
const PASSWORD = 'a-test-password-12345';
// Argon2id hash of PASSWORD, generated by scripts/hash-password.ts.
process.env['UI_ENABLED'] = 'true';
process.env['ADMIN_USERNAME'] = USER;
process.env['MCP_SECRET'] = 'e'.repeat(64);
process.env['TOKEN_ENC_KEY'] = 'd'.repeat(64);
process.env['DB_PATH'] = join(mkdtempSync(join(tmpdir(), 'tally-web-')), 'web.db');
process.env['CRON_ENABLED'] = 'false';
process.env['COOKIE_SECURE'] = 'false';

const { hashPassword } = await import('../src/auth/password.ts');
process.env['ADMIN_PASSWORD_HASH'] = await hashPassword(PASSWORD);

const { createApp } = await import('../src/index.ts');
const { getDb } = await import('../src/db.ts');
const { upsertAccount } = await import('../src/store.ts');

let server: Server;
let base: string;

beforeAll(async () => {
  server = createApp().listen(0);
  await new Promise<void>((r) => server.once('listening', r));
  base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
});

afterAll(() => server.close());

async function login(): Promise<{ cookie: string; csrf: string }> {
  const res = await fetch(`${base}/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ username: USER, password: PASSWORD }),
    redirect: 'manual',
  });
  const setCookie = res.headers.get('set-cookie') ?? '';
  const cookie = setCookie.split(';')[0] ?? '';
  const home = await fetch(`${base}/`, { headers: { cookie } });
  const body = await home.text();
  const csrf = /name="_csrf" value="([^"]+)"/.exec(body)?.[1] ?? '';
  return { cookie, csrf };
}

describe('the UI is gated', () => {
  it('redirects an anonymous visitor to the login page', async () => {
    for (const path of ['/', '/settings', '/connections', '/security']) {
      const res = await fetch(`${base}${path}`, { redirect: 'manual' });
      expect(res.status, path).toBe(303);
      expect(res.headers.get('location')).toBe('/login');
    }
  });

  it('serves a login form', async () => {
    const res = await fetch(`${base}/login`);
    expect(res.status).toBe(200);
    expect(await res.text()).toContain('name="password"');
  });

  it('leaves the MCP endpoint reachable without a session', async () => {
    const res = await fetch(`${base}/mcp/${'e'.repeat(64)}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', accept: 'application/json, text/event-stream' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }),
    });
    expect(res.status).toBe(200);
  });
});

describe('sign-in', () => {
  it('rejects a wrong password with the same message as a wrong username', async () => {
    const wrongPass = await fetch(`${base}/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ username: USER, password: 'nope' }),
      redirect: 'manual',
    });
    const wrongUser = await fetch(`${base}/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ username: 'someone', password: PASSWORD }),
      redirect: 'manual',
    });
    expect(wrongPass.status).toBe(401);
    expect(wrongUser.status).toBe(401);
    expect(await wrongPass.text()).toContain('Incorrect username or password');
    expect(await wrongUser.text()).toContain('Incorrect username or password');
  });

  it('sets an HttpOnly, SameSite session cookie on success', async () => {
    const res = await fetch(`${base}/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ username: USER, password: PASSWORD }),
      redirect: 'manual',
    });
    expect(res.status).toBe(303);
    const cookie = res.headers.get('set-cookie') ?? '';
    expect(cookie).toContain('tally_sid=');
    expect(cookie).toContain('HttpOnly');
    expect(cookie).toContain('SameSite=Lax');
  });

  it('lets a signed-in visitor see the overview', async () => {
    const { cookie } = await login();
    const res = await fetch(`${base}/`, { headers: { cookie } });
    expect(res.status).toBe(200);
    const body = await res.text();
    expect(body).toContain('Net worth');
    expect(body).toContain('Sign out');
  });
});

describe('CSRF', () => {
  it('refuses a state-changing POST with no token', async () => {
    const { cookie } = await login();
    const res = await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ PLAID_CLIENT_ID: 'evil' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(403);
  });

  it('refuses a wrong token', async () => {
    const { cookie } = await login();
    const res = await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: 'wrong', PLAID_CLIENT_ID: 'evil' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(403);
  });

  it('accepts a valid token and stores the setting', async () => {
    const { cookie, csrf } = await login();
    const res = await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf, PLAID_CLIENT_ID: 'client-123' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(303);
    const page = await (await fetch(`${base}/settings`, { headers: { cookie } })).text();
    expect(page).toContain('client-123');
  });

  it('never echoes a stored secret back to the page', async () => {
    const { cookie, csrf } = await login();
    await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf, PLAID_SECRET: 'top-secret-plaid-value' }),
      redirect: 'manual',
    });
    const page = await (await fetch(`${base}/settings`, { headers: { cookie } })).text();
    expect(page).not.toContain('top-secret-plaid-value');
    expect(page).toContain('unchanged');
  });
});

describe('response hardening', () => {
  it('sends a strict CSP and anti-framing headers', async () => {
    const res = await fetch(`${base}/login`);
    const csp = res.headers.get('content-security-policy') ?? '';
    expect(csp).toContain("default-src 'none'");
    expect(csp).toContain("frame-ancestors 'none'");
    expect(csp).not.toContain("'unsafe-inline'");
    expect(res.headers.get('x-frame-options')).toBe('DENY');
    expect(res.headers.get('referrer-policy')).toBe('no-referrer');
    expect(res.headers.get('cache-control')).toBe('no-store');
  });
});

describe('escaping institution-supplied text', () => {
  it('does not render a script tag smuggled through an account name', async () => {
    upsertAccount(getDb(), {
      id: 'plaid:xss',
      source: 'plaid',
      institution: '<script>alert(1)</script>',
      name: '"><img src=x onerror=alert(1)>',
      mask: null,
      account_category: 'DEPOSITORY',
      account_subtype: null,
      registered_type: 'NON_REG',
      currency: 'CAD',
      balance: 10,
      balance_cad: 10,
      available: null,
      active: true,
      status: 'ok',
      item_id: null,
    });
    const { cookie } = await login();
    const body = await (await fetch(`${base}/`, { headers: { cookie } })).text();
    // The payload must survive only as inert text: no raw tag may reach the
    // document. The literal substring "onerror=alert(1)" is fine once the
    // angle brackets around it are entities — it is the `<img` that matters.
    expect(body).not.toContain('<script>alert(1)</script>');
    expect(body).not.toContain('<img src=x');
    expect(body).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
    expect(body).toContain('&lt;img src=x onerror=alert(1)&gt;');
  });
});

describe('sign-out', () => {
  it('invalidates the session server-side, not just in the browser', async () => {
    const { cookie, csrf } = await login();
    const out = await fetch(`${base}/logout`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf }),
      redirect: 'manual',
    });
    expect(out.status).toBe(303);
    const after = await fetch(`${base}/`, { headers: { cookie }, redirect: 'manual' });
    expect(after.status).toBe(303);
  });

  it('says why, when the idle timer was what signed you out', async () => {
    const { cookie } = await login();
    const out = await fetch(`${base}/logout`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ idle: '1' }),
      redirect: 'manual',
    });
    expect(out.headers.get('location')).toBe('/login?idle=1');
    const login_ = await fetch(`${base}/login?idle=1`);
    expect(await login_.text()).toMatch(/minutes of inactivity/);
  });
});

describe('the activity heartbeat', () => {
  it('accepts a signed-in caller and refuses everyone else', async () => {
    const { cookie } = await login();
    const ok = await fetch(`${base}/session/ping`, { method: 'POST', headers: { cookie } });
    expect(ok.status).toBe(204);

    const anon = await fetch(`${base}/session/ping`, { method: 'POST' });
    expect(anon.status).toBe(401);
  });

  it('is wired into the page, so an abandoned tab signs itself out', async () => {
    const { cookie } = await login();
    const body = await (await fetch(`${base}/`, { headers: { cookie } })).text();
    expect(body).toContain('/session/ping');
    // The timeout the page enforces must be the one the server enforces.
    expect(body).toContain(String(30 * 60 * 1000));
    expect(inlineHandlers(body)).toEqual([]);
  });
});

describe('two-factor enrolment', () => {
  async function form(
    path: string,
    cookie: string,
    fields: Record<string, string>,
  ): Promise<Response> {
    return fetch(`${base}${path}`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(fields),
      redirect: 'manual',
    });
  }

  it('walks the whole flow: enrol, reject a bad code, enable, enforce, disable', async () => {
    const { totp } = await import('../src/auth/totp.ts');
    const { cookie, csrf } = await login();

    // 1. Starting enrolment shows a secret but does NOT enable anything yet —
    //    a half-finished enrolment must never lock the account out.
    const start = await form('/security/totp/start', cookie, { _csrf: csrf });
    const startBody = await start.text();
    expect(start.status, startBody.slice(0, 300)).toBe(200);
    const secret = /<div class="code-block">([A-Z2-7]{32})<\/div>/.exec(startBody)?.[1] ?? '';
    expect(secret).toMatch(/^[A-Z2-7]{32}$/);
    expect(startBody).toContain('otpauth://totp/');

    const stillOff = await (await fetch(`${base}/security`, { headers: { cookie } })).text();
    expect(stillOff).toContain('not enabled');

    // 2. A wrong code must not enable it.
    const bad = await form('/security/totp/confirm', cookie, {
      _csrf: csrf,
      secret,
      code: '000000',
    });
    expect(bad.headers.get('location')).toContain('err=');
    const afterBad = await (await fetch(`${base}/security`, { headers: { cookie } })).text();
    expect(afterBad).toContain('not enabled');

    // 3. The right code enables it.
    const good = await form('/security/totp/confirm', cookie, {
      _csrf: csrf,
      secret,
      code: totp(secret),
    });
    expect(good.headers.get('location')).toContain('ok=');
    const afterGood = await (await fetch(`${base}/security`, { headers: { cookie } })).text();
    expect(afterGood).toContain('pill ok">enabled');

    // 4. Sign-in is now two steps: the password buys only a pending session.
    const step1 = await fetch(`${base}/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ username: USER, password: PASSWORD }),
      redirect: 'manual',
    });
    expect(step1.status).toBe(303);
    expect(step1.headers.get('location')).toBe('/login/verify');
    const pendingCookie = (step1.headers.get('set-cookie') ?? '').split(';')[0] ?? '';

    // That pending cookie must grant nothing.
    const blocked = await fetch(`${base}/`, {
      headers: { cookie: pendingCookie },
      redirect: 'manual',
    });
    expect(blocked.status).toBe(303);
    expect(blocked.headers.get('location')).toBe('/login/verify');

    const verifyPage = await (
      await fetch(`${base}/login/verify`, { headers: { cookie: pendingCookie } })
    ).text();
    const verifyCsrf = /name="_csrf" value="([^"]+)"/.exec(verifyPage)?.[1] ?? '';
    expect(verifyCsrf).not.toBe('');

    const wrongCode = await fetch(`${base}/login/verify`, {
      method: 'POST',
      headers: { cookie: pendingCookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: verifyCsrf, code: '000000' }),
      redirect: 'manual',
    });
    expect(wrongCode.status).toBe(401);

    const step2 = await fetch(`${base}/login/verify`, {
      method: 'POST',
      headers: { cookie: pendingCookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: verifyCsrf, code: totp(secret) }),
      redirect: 'manual',
    });
    expect(step2.status).toBe(303);
    expect(step2.headers.get('location')).toBe('/');

    // The session id must have been rotated — session fixation protection.
    const fullCookie = (step2.headers.get('set-cookie') ?? '').split(';')[0] ?? '';
    expect(fullCookie).not.toBe(pendingCookie);
    const home = await fetch(`${base}/`, { headers: { cookie: fullCookie }, redirect: 'manual' });
    expect(home.status).toBe(200);
    // and the old pending id must be dead
    const reused = await fetch(`${base}/`, { headers: { cookie: pendingCookie }, redirect: 'manual' });
    expect(reused.status).toBe(303);
    expect(reused.headers.get('location')).toBe('/login');

    // 5. Disabling requires a current code, not just a session.
    const refused = await form('/security/totp/disable', cookie, { _csrf: csrf, code: '000000' });
    expect(refused.headers.get('location')).toContain('err=');
    expect(await (await fetch(`${base}/security`, { headers: { cookie } })).text()).toContain(
      'pill ok">enabled',
    );

    const disabled = await form('/security/totp/disable', cookie, {
      _csrf: csrf,
      code: totp(secret),
    });
    expect(disabled.headers.get('location')).toContain('ok=');
    expect(await (await fetch(`${base}/security`, { headers: { cookie } })).text()).toContain(
      'not enabled',
    );
  });
});

describe('Plaid setup panel', () => {
  it('shows the exact values the server sends, so setup is not error-by-error', async () => {
    const { cookie, csrf } = await login();
    // Credentials must be present for the panel's provider rows to be meaningful.
    await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf, PLAID_CLIENT_ID: 'cid', PLAID_SECRET: 'sec' }),
      redirect: 'manual',
    });
    const body = await (await fetch(`${base}/connections`, { headers: { cookie } })).text();

    expect(body).toContain('Plaid dashboard setup');
    // The redirect URI must be rendered exactly, derived from the request host.
    expect(body).toContain('/connections/oauth');
    expect(body).toContain('Allowed redirect URI');
    // Environment and products are what a mismatched dashboard config turns on.
    expect(body).toContain('Environment');
    expect(body).toContain('transactions');
    expect(body).toContain('optional: liabilities');
  });
});

describe('linking is scoped to the named profile', () => {
  it('refuses to link without an explicit profile, rather than defaulting', async () => {
    const { cookie, csrf } = await login();
    // Falling back to the default here would consume the wrong profile's Plaid
    // Item allowance and attribute the accounts to the wrong person, silently.
    const res = await fetch(`${base}/api/plaid/link-token`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/json', 'x-csrf-token': csrf },
      body: JSON.stringify({}),
      redirect: 'manual',
    });
    expect(res.status).toBe(400);
    expect((await res.json() as { error: string }).error).toMatch(/profile is required/);
  });

  it('refuses an unknown profile', async () => {
    const { cookie, csrf } = await login();
    const res = await fetch(`${base}/api/plaid/exchange`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/json', 'x-csrf-token': csrf },
      body: JSON.stringify({ profile: 'ghost', public_token: 'x' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(400);
    expect((await res.json() as { error: string }).error).toMatch(/no such profile/);
  });

  it('embeds the active profile in the page so the client can send it', async () => {
    const { cookie, csrf } = await login();
    await fetch(`${base}/settings`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf, PLAID_CLIENT_ID: 'cid', PLAID_SECRET: 'sec' }),
      redirect: 'manual',
    });
    const body = await (await fetch(`${base}/connections`, { headers: { cookie } })).text();
    expect(body).toContain('const PROFILE = "me"');
    // and it must survive Plaid's OAuth round trip, which returns with no query
    expect(body).toContain('tally_profile');
  });
});

describe('disconnecting a bank', () => {
  it('reports an unknown item rather than silently doing nothing', async () => {
    const { cookie, csrf } = await login();
    const res = await fetch(`${base}/connections/remove`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf, item_id: 'nope', profile: 'me' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(303);
    expect(decodeURIComponent(res.headers.get('location') ?? '')).toContain('unknown Plaid item_id');
  });

  it('requires a CSRF token — revoking a token is destructive', async () => {
    const { cookie } = await login();
    const res = await fetch(`${base}/connections/remove`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ item_id: 'nope', profile: 'me' }),
      redirect: 'manual',
    });
    expect(res.status).toBe(403);
  });
});

describe('connector URL', () => {
  it('shows a secret-free MCP URL and OAuth instructions', async () => {
    const { cookie } = await login();
    const body = await (await fetch(`${base}/security`, { headers: { cookie } })).text();
    expect(body).toContain('/mcp</div>');
    expect(body).toContain('it contains no secret');
    expect(body).toContain('Authorized apps');
    // The secret must never sit in the source of a page nobody asked for it on.
    expect(body).not.toContain('e'.repeat(64));
  });

  it('still reveals the legacy URL only on an explicit POST while the route is enabled', async () => {
    const { cookie, csrf } = await login();
    const res = await fetch(`${base}/security/connector`, {
      method: 'POST',
      headers: { cookie, 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ _csrf: csrf }),
    });
    expect(await res.text()).toContain(`/mcp/${'e'.repeat(64)}`);
  });
});

describe('never-synced Plaid items', () => {
  it('detects an Item that was linked but never read, and ignores broken ones', async () => {
    const { unsyncedItems } = await import('../src/sources/plaid.ts');
    const db = getDb();
    const ins = db.prepare(
      `INSERT OR REPLACE INTO plaid_items
         (item_id, institution_name, access_token, status, last_synced_at, profile_id, created_at, updated_at)
       VALUES (?, ?, 'tok', ?, ?, 'me', '', '')`,
    );
    ins.run('fresh', 'Newly linked', 'ok', null);
    ins.run('read', 'Already read', 'ok', '2026-09-18T02:00:00Z');
    // Awaiting repair: it cannot sync until re-authenticated, so chasing it
    // would just log failures forever.
    ins.run('broken', 'Needs repair', 'login_required', null);

    const pending = unsyncedItems(db).map((i) => i.item_id);
    expect(pending).toContain('fresh');
    expect(pending).not.toContain('read');
    expect(pending).not.toContain('broken');

    for (const id of ['fresh', 'read', 'broken']) {
      db.prepare('DELETE FROM plaid_items WHERE item_id = ?').run(id);
    }
  });
});

describe('no inline event handlers anywhere', () => {
  it('never emits on*= attributes, which a nonce CSP blocks silently', async () => {
    const { cookie } = await login();
    // This class of bug is invisible: the markup looks right, the handler just
    // never runs. The profile dropdown shipped broken for exactly this reason.
    for (const path of ['/', '/transactions', '/merchants', '/connections', '/settings', '/security', '/profiles']) {
      const body = await (await fetch(`${base}${path}`, { headers: { cookie } })).text();
      const handlers = inlineHandlers(body);
      expect(handlers, `${path} has inline handlers: ${handlers.join(', ')}`).toEqual([]);
    }
  });
});
